import { z } from 'zod';
import { RISK_LEVELS, VITAL_RANGES } from '@/lib/triage/vitals';

const ranged = (key: keyof typeof VITAL_RANGES) => {
  const [min, max] = VITAL_RANGES[key];
  return z.number().min(min).max(max).optional();
};

export const vitalsSchema = z.object({
  temperatureF: ranged('temperatureF'),
  systolicBp: ranged('systolicBp'),
  diastolicBp: ranged('diastolicBp'),
  oxygenSaturation: ranged('oxygenSaturation'),
  heartRate: ranged('heartRate'),
  respiratoryRate: ranged('respiratoryRate'),
  bloodGlucose: ranged('bloodGlucose'),
});

export const triageRequestSchema = z.object({
  /**
   * Idempotency key generated by the offline client. Lets a replayed sync
   * queue item resolve to the existing assessment instead of a duplicate.
   */
  clientRequestId: z.string().uuid(),

  symptoms: z.array(z.string().min(2).max(120)).min(1).max(25),

  /** Free-text field-worker notes. Treated as untrusted data, not instructions. */
  notes: z.string().max(1_500).optional(),

  ageYears: z.number().int().min(0).max(120).optional(),
  sex: z.enum(['male', 'female', 'other', 'undisclosed']).optional(),
  knownConditions: z.array(z.string().max(80)).max(15).optional(),
  vitals: vitalsSchema.default({}),
});

export type TriageRequest = z.infer<typeof triageRequestSchema>;

/** Shape the model is constrained to emit. */
export const aiTriageOutputSchema = z.object({
  riskLevel: z.enum(RISK_LEVELS),
  provisionalClinicalCue: z.string().min(10).max(1_200),
  considerations: z
    .array(
      z.object({
        condition: z.string(),
        supportingEvidence: z.string(),
        contextRefs: z.array(z.string()).max(6),
      }),
    )
    .max(5),
  redFlags: z.array(z.string()).max(10),
  recommendedAction: z.enum([
    'HOME_CARE_WITH_ADVICE',
    'ROUTINE_MO_REVIEW',
    'PRIORITY_MO_REVIEW_SAME_DAY',
    'IMMEDIATE_REFERRAL',
  ]),
  groundingSufficient: z.boolean(),
  reasoningSummary: z.string().max(800),
});

export type AiTriageOutput = z.infer<typeof aiTriageOutputSchema>;

/** JSON Schema handed to Gemini via responseSchema. */
export const geminiResponseSchema = {
  type: 'object',
  properties: {
    riskLevel: { type: 'string', enum: [...RISK_LEVELS] },
    provisionalClinicalCue: { type: 'string' },
    considerations: {
      type: 'array',
      items: {
        type: 'object',
        properties: {
          condition: { type: 'string' },
          supportingEvidence: { type: 'string' },
          contextRefs: { type: 'array', items: { type: 'string' } },
        },
        required: ['condition', 'supportingEvidence', 'contextRefs'],
        propertyOrdering: ['condition', 'supportingEvidence', 'contextRefs'],
      },
    },
    redFlags: { type: 'array', items: { type: 'string' } },
    recommendedAction: {
      type: 'string',
      enum: [
        'HOME_CARE_WITH_ADVICE',
        'ROUTINE_MO_REVIEW',
        'PRIORITY_MO_REVIEW_SAME_DAY',
        'IMMEDIATE_REFERRAL',
      ],
    },
    groundingSufficient: { type: 'boolean' },
    reasoningSummary: { type: 'string' },
  },
  required: [
    'riskLevel',
    'provisionalClinicalCue',
    'considerations',
    'redFlags',
    'recommendedAction',
    'groundingSufficient',
    'reasoningSummary',
  ],
  propertyOrdering: [
    'riskLevel',
    'provisionalClinicalCue',
    'considerations',
    'redFlags',
    'recommendedAction',
    'groundingSufficient',
    'reasoningSummary',
  ],
} as const;
